name: Download SBI Rates PDF

on:
  schedule:
    - cron: '15 14 * * *'
    - cron: '15 19 * * *'
  workflow_dispatch:

jobs:
  download-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get current date and time
      id: date
      run: echo "::set-output name=timestamp::$(date -u +'%Y/%m/%Y-%m-%d-%H:%M')"

    - name: Download PDF
      run: |
        TIMESTAMP=${{ steps.date.outputs.timestamp }}
        mkdir -p sbi-rates/${TIMESTAMP%/*}
        curl -o sbi-rates/${TIMESTAMP}.pdf https://www.sbi.co.in/documents/16012/1400784/FOREX_CARD_RATES.pdf

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sbi-rates/
        git commit -m "Add SBI rates PDF for ${{ steps.date.outputs.timestamp }}"
        git push
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
